[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Bootstrap = "e28b5b4c-05e8-5b66-bc03-6f0c0a0a06e0"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
