[assets]
git-tree-sha1 = "4a6957585f2c5b59544dda44c60c3236437e93aa"

[[assets.download]]
sha256 = "0bd46e3081658fdd7aa4bb5d0e6b97e6ccfa7cb254c8de6154d7791618cf6031"
url = "https://github.com/JuliaPlots/Makie.jl/releases/download/assets-0.1.2/assets-0.1.2.tar.gz"
