[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
