name = "ReferenceUpdater"
uuid = "0b7a0440-c633-4ac4-9779-d1266ef64952"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com>"]
version = "0.1.0"

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFMPEG_jll = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
ghr_jll = "07c12ed4-43bc-5495-8a2a-d5838ef8d533"

[compat]
Bonito = "3, 4"
Colors = "0.12, 0.13.0"
DelimitedFiles = "1.9.1"
FFMPEG_jll = "6.1.2, 7"
FileIO = "1.16.6"
HTTP = "1"
Statistics = "1.11.1"
